language: node_js

node_js:
- 6

branches:
  only:
  - auto-deployment

addons:
  ssh_known_hosts:
  - ubuntu-ea.cloudapp.net:22

before_install:
- openssl aes-256-cbc -K $encrypted_1f03ec56ea65_key -iv $encrypted_1f03ec56ea65_iv -in ubuntu_ea_pvk.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- sed -i "s/__GH_TOKEN__/${GH_TOKEN}/" _config.yml

install:
- npm install hexo-cli -g
- npm install
- git config --global user.name "winterTTr"
- git config --global user.email "winterTTr@gmail.com"

script:
- hexo clean
- hexo generate
- hexo deploy
