# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Life & Note - winterTTr
subtitle: winterTTr's Blog
description: Memo down pieces of Life
author: winterTTr
language: en
timezone:
avatar: /images/avatar.jpg
since: 2015

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://winterTTr.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - baidu_verify_F0n02D9Rhz.html
  - a23372d1a05807743aa8bd094cc75e38.txt
  - sogousiteverification.txt.html
  - static/**/*

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: git
  repo:
    github: https://github.com/winterTTr/winterTTr.github.io.git
#    gitcafe: https://gitcafe.com/winterTTr/winterTTr.git
- type: rsync
  host: ubuntu-ea.cloudapp.net
  user: rsync
  root: /var/www/html
  port: 22
  delete: true
  verbose: true


# rss
feed:
  type: atom
  path: atom.xml
  limit: 0

# friend link
links_title: Favorate Links

links:
  少数派: http://sspai.com
  Master Emacs: https://www.masteringemacs.org/


# site map
sitemap:
  path: sitemap.xml


# Qiniu Config
qiniu:
  offline: false
  sync: true
  bucket: winterttr-github-io
  access_key: 8k5DN11zjqRdx7TgHS0S7R9RoCnxaQzSpV8ptBqy
  secret_key: 4hJy9NbPpzM4iY9xtLDjxKuZjV4tOyob4OdQIOLU
  dirPrefix: static
  urlPrefix: http://7xljtv.com1.z0.glb.clouddn.com/static
  local_dir: static
  update_exist: true
  image: 
    folder: images
    extend: 
  js:
    folder: js
  css:
    folder: css

# baidu sitemap
baidusitemap:
  path: baidusitemap.xml



## Third-party services

# Duoshuo ShortName
#duoshuo_shortname:

# Disqus
disqus_shortname: winterTTr

# Baidu Analytics ID
baidu_analytics: 12217b6eff7690192f4e4469013eee76

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification: D_sz64DZ1b38eNfy3sac0h9jaE2HKjSg0qeS_6Ar_aw


# Google Analytics
google_analytics: UA-67136287-1

# CNZZ count
#cnzz_siteid:

# Share
jiathis: true

# Baidu Share
# Available value:
#    button | slide
baidushare:
  type: button

# Share
#duoshuo_share: true
duoshuo_hotartical: true


# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: 0
  #admin_nickname: Author

# Swiftype Search API Key
swiftype_key: WRpxR8GrCr4jNe6LcLyU
